server:
  port: 9000
#  servlet:
#    context-path: /feignMaster
spring:
  application:
    name: feign-master
eureka:
  client:
    service-url:
      defaultZone: http://songzhao/eurekaServerMaster/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}  # hystrix-dashboard
    #home-page-url-path: /feignMaster
    metadata-map:
      cluster: BASIC  # hystrix-dashboard
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 180000
management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1