server:
  port: 9100
  servlet:
    context-path: /feignSlave
spring:
  application:
    name: feign-slave
  cloud:
    loadbalancer:
      ribbon:
        enabled: false  #由于Ribbon负载均衡器现在处于维护模式，我们建议改用Spring Cloud LoadBalancer，它也包含在Eureka启动器中。
eureka:
  client:
    refresh:
      enable: false  # 禁止客户端刷新.因为刷新同时客户端会取消注册暂时失联。
    service-url:
      defaultZone: http://user:user@songzhao/eurekaServerMaster/eureka/
    healthcheck:
      enabled: true
  instance:
    home-page-url-path: /feignSlave
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 15
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}  # hystrix-dashboard
    metadata-map:
      cluster: BASIC
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 180000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 180000  #缺省为1000
management:
  endpoints:
    web:
      exposure:
        include: "*"
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000

#  eureka:
#    enabled: false
