server:
  port: 7000
#  servlet:
#    context-path: /turbineMaster
spring:
  application:
    name: turbine-master
eureka:
  client:
    service-url:
      defaultZone: http://songzhao/eurekaServerMaster/eureka/
#  instance:
#    instance-id: ${spring.application.name}:${server.port}
turbine:    #   instance_id 遵循规则。
  #  cluster-name-expression: "'default'"
  cluster-name-expression: metadata['cluster']    #  客户端配置 metadata cluster 。
  aggregator:
    cluster-config: BASIC    # need provider statement
  app-config: feign-master,feign-slave
  instanceUrlSuffix: /actuator/hystrix.stream    # all service suffix
#  instanceUrlSuffix:    #   Specify service suffixes
#    feign-master: feignMaster/actuator/hystrix.stream    #  home-page-url-path:
#    feign-slave: feignSlave/actuator/hystrix.stream

