server:
  port: 7000
#  servlet:
#    context-path: /turbineMaster
spring:
  application:
    name: turbine-master
eureka:
  client:
    service-url:
      defaultZone: http://user:user@songzhao/eurekaServerMaster/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}


turbine:
  #  cluster-name-expression: "'default'"
  cluster-name-expression: metadata['cluster']    #  客户端配置 metadata cluster 。
  aggregator:
    cluster-config: BASIC,BASICT    # need provider statement
  app-config: feign-master,feign-slave
  instanceUrlSuffix:
    BASIC: feignMaster/actuator/hystrix.stream
    BASICT: feignSlave/actuator/hystrix.stream

